version: '3.2'

services:
  cinema-catalog-ms:
    build:
      context: './api/cinema-catalog-service'
    ports:
      - '9002:9002'
    volumes: 
      - './api/cinema-catalog-service:/home/node/app'
  
  movies-ms:
    build: 
      context: './api/movies-service'
    
    ports: 
      - '9001:9001'
    volumes: 
      - './api/movies-service:/home/node/app'

  api-gateway:
    build: 
      context: './api/api-gateway'
    ports:
      - '9000:9000'

    links: 
      - 'movies-ms'
      - 'cinema-catalog-ms'
    volumes: 
      - './api/api-gateway:/home/node/app'

  web:
    build: 
      context: './web'
    ports: 
      - '3000:3000'
    links: 
      - 'api-gateway'
    volumes: 
      - './web:/app'